version: '3.8'

services:
  url-shortener:
    build:
      context: ./backend
    container_name: url-shortener-app
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env 
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/url_shortener
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
