version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/url_shortener
  
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: